gmap_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'gmap_app'

urlpatterns = [
    # ex: http://localhost:8000/gmap_app/show_map/
    url(r'^store_addresses/$', views.store_addresses, name='store_addresses'),
    
]

gmaps_fusion/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^gmap_app/', include('gmap_app.urls')),
    url(r'^admin/', admin.site.urls),
]

gmap_app/models.py
from django.db import models

class Places(models.Model):
    address = models.CharField(max_length=100)
    latitude = models.CharField(max_length=100, default='')
    longitude = models.CharField(max_length=100, default='')
    
    def __unicode__(self):
        return self.address

gmap_app/forms.py
from django.forms import ModelForm
from gmap_app.models import Places

class PlacesForm(ModelForm):
  class Meta:
      model = Places
      fields = ('address', 'latitude', 'longitude',)

gmap_app/views.py
import textwrap
import pprint

from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views.generic.base import View

from gmap_app.forms import PlacesForm
from gmap_app.models import Places

def remove_all_places():
  ''' Removes all places from stored models'''
  existing_items = Places.objects.all()
  print(" Removing [%d] existing items"%len(existing_items))
  for item in existing_items:
    item.delete()

def address_is_distinct():
  ''' Looks for duplicates in database and removes them'''
  existing_items = Places.objects.all()
  print(" Removing existing duplicated addresses")
  for address in Places.objects.values_list('address', flat=True).distinct():
    Places.objects.filter(pk__in=Places.objects.filter(address=address).values_list('id', flat=True)[1:]).delete()

def store_addresses(request):
    ''' 
    View to get valid google addresses from hidden inputs
    '''
    
    ## The first time the page is loaded or whenever is reloaded via browser
    ##   it will remove all items
    if request.method == 'GET':
      remove_all_places()
    elif request.method == 'POST':
      ## Preparing data dynamically for store in model
      print(" Parsing URL encoded data from POST method")
      modelsPlaces = ['address', 'latitude', 'longitude']
      postDict = request.POST.dict()
      postKeys = postDict.keys()
      placesDict = {}
      
      ## Parsing URL encoded data for storing one-by-one
      for modelKey in modelsPlaces:
        for key in postKeys:
          if key.startswith(modelKey):
            item = postDict[key]
            item_id = key[len(modelKey):]
            item_id_exist = item_id in placesDict.keys()
            if item_id not in placesDict.keys():
              placesDict[item_id]={}
            placesDict[item_id].update({modelKey:item})

      ## Store any places found from URL encoded
      if len(placesDict)>0:
        placesDictKeys = placesDict.keys()
        print(" Found [%d] elements after submit"%len(placesDictKeys))
        for _id in placesDictKeys:
          form = PlacesForm(placesDict[_id])
          if form.is_valid():
            print("  Creating model forms for item ID [%s]"%_id)
            form.save()

      address_is_distinct()
    return render(request, 'gmap_app/map.html')

gmap_app/templates/gmap_app/map.html
{% block start_body %}
<!DOCTYPE html>
<html>
  <head>
    <title>Google map fusion tables</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
{% endblock start_body %}

{% block api %}
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCS938OvLrM1AqdNtUhZza1B98GkJaeKjY&callback=initMap">
    </script>
{% endblock api %}

{% block display_map %}
    
    <div id="map" style="width: 600px; height: 600px;"></div>
      <script>
      
	var labelIndex = 0;
	var map;
	var layer;
	var places=[]
	
	/*
	*  Initialises map funciotns
	*/
	function initMap() {
	  map = new google.maps.Map(document.getElementById('map'), {
	    zoom: 16,
	    center: {lat: 51.50083552254009, lng: -0.12462615966796875 }
	  });

	  var geocoder = new google.maps.Geocoder();

	  // Waits for button click to display and list markers 
	  document.getElementById('submit').addEventListener('click', function() {
	    ListMarkers(places);
	    ShowMarkers(places, map);
	    
	  });
        
	  map.addListener('click', function(e) {
	    CollectMarkerAddress(geocoder, e.latLng, map);
	  });
	  
	}
	
	/*
	*  Displays markers on a map from an array
	*  of valid addresses
	*/
	function ShowMarkers(places, map) {
	  for (var i=0; i<places.length; i++) {
	    address = places[i]['address']
	    latLng = places[i]['latLng']
	    id = places[i]['id']
	    
// 	    console.log("["+id+"]:"+address+ "("+latLng.lat()+", "+latLng.lng()+")");
	    
	    // Setting marker with latitude and longitude
	    var marker = new google.maps.Marker({
	      position: latLng,
	      map: map
	    });
	    map.panTo(latLng);
		
	    // Creating label for marker with found address
	    var infowindow = new google.maps.InfoWindow;
	    var address = '['+id+'] '+address;
	    infowindow.setContent(address);
	    infowindow.open(map, marker);
	  }
	}
	
	/*
	*  Is activated on every map clikc and looks for an
	*  address from Google API. Stores valid addresses
	*  as JSON in an Array
	*/ 
	function CollectMarkerAddress(geocoder, latLng, map) {
	  labelIndex++;
	  
	  // Use Google API to collecting Geocodded 
	  //  address based in latitude and longitude
	  geocoder.geocode( {'location': latLng}, function(results, status) {
	  
	    // Place markers only for valid addresses,
	    // BUG: Filter empty places addressed with name of country
	    //      (e.g open sea= 51.77463825786987, 1.77978515625) 
	    // 1) Has a post code
	    // 2) Has Province. Country -> Not valid, less than 3 comma separated 
	    if (status === 'OK') {
	      if (results[0]) {
		// Create an array of places
		var place = {
		  'address':results[0].formatted_address,
		  'latLng' :latLng,
		  'id':labelIndex}
		places.push(place)
	      } 
	    } 
	  });
	}
	
	maps.event.addDomListener(window, 'load', initialize);

	/*
	*  Generates a dynamic list of addresses
	*  based in places
	*/
	function ListMarkers(places) {
	    // Making region visible
	    var divList = document.getElementById('list-places');
	    if (divList.style.display === 'none') {
		divList.style.display = 'block';
	    }
	    
	    // Removing any alrady existing listed elements 
	    var placesSpace = document.getElementById("places-space")
	    if (placesSpace.hasChildNodes()){
	      var listChildren = placesSpace.children;
	      if (listChildren.length>0)
	      {
		while(placesSpace.firstChild) {
		  placesSpace.removeChild(placesSpace.firstChild);
		}
	      }
	    }
	    
	    // Create List of places
	    for (var i=0; i<places.length; i++) {
	      address = places[i]['address']
	      id = places[i]['id']
	      latLng = places[i]['latLng']
	      var line = "["+id+"] "+address
	      var node = document.createElement("LI");
	      var textnode = document.createTextNode(line);
	      node.appendChild(textnode);
	      	      
	      // Generate hidden elements for sending to Django views
	      var inputAddress = document.createElement("input");
	      inputAddress.type = 'hidden';
	      inputAddress.value = address;
	      inputAddress.name = "address"+id
	      node.appendChild(inputAddress);
	      
	      var inputLat = document.createElement("input");
	      inputLat.type = 'hidden';
	      inputLat.value = latLng.lat();
	      inputLat.name = "latitude"+id
	      node.appendChild(inputLat);

	      var inputLng = document.createElement("input");
	      inputLng.type = 'hidden';
	      inputLng.value = latLng.lng();
	      inputLng.name = "longitude"+id
	      node.appendChild(inputLng);
	      
	      document.getElementById("places-space").appendChild(node);
	      
	    }
	    
	}
	

      </script>
    
{% endblock display_map %}

{% block list_markers %}
  
  <div id="floating-panel" style="text-align:center">
    <input id="submit" type="submit" value="Show Addresses" style="width: 300px; margin: 0 auto;">
  </div>  
  
  <form action="{% url 'gmap_app:store_addresses' %}" method="POST">
    {% csrf_token %}
    <div id="list-places" style =''>
      <ul id="places-space">
      </ul>
    </div>
  <input id="submit" type="submit" value="Submit">

  </form>
{% endblock list_markers %}

{% block end_body %}
  </body>
</html>
{% endblock end_body %}